name: workshop
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^3.1.0
  get_it: ^3.0.0+1

  auto_size_text: ^2.1.0
  animator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Yellowtail
      fonts:
        - asset: fonts/Yellowtail-Regular.ttf